--------------------------------------------------------
--  파일이 생성됨 - 화요일-4월-02-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "SONG"."CUSTOMER" 
   (	"CUS_NUMBER" VARCHAR2(20 BYTE), 
	"CUS_NAME" VARCHAR2(20 BYTE), 
	"CUS_PHONE" VARCHAR2(20 BYTE), 
	"CUS_DATA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "SONG"."PRODUCT" 
   (	"PRO_CODE" VARCHAR2(20 BYTE), 
	"PRO_NAME" VARCHAR2(50 BYTE), 
	"PRO_PRICE" NUMBER, 
	"PRO_QUANTITY" NUMBER, 
	"PRO_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION
--------------------------------------------------------

  CREATE TABLE "SONG"."TRANSACTION" 
   (	"TRA_ORDER" NUMBER, 
	"TRA_QUANTITY" NUMBER, 
	"TRA_PRICE" NUMBER, 
	"TRA_DATE" DATE, 
	"TRA_SALE" NUMBER, 
	"CUS_NUMBER" VARCHAR2(20 BYTE), 
	"PRO_CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SONG.CUSTOMER
SET DEFINE OFF;
REM INSERTING into SONG.PRODUCT
SET DEFINE OFF;
Insert into SONG.PRODUCT (PRO_CODE,PRO_NAME,PRO_PRICE,PRO_QUANTITY,PRO_DATE) values ('0100000101','빨간 코튼상의',20000,12,to_date('19/04/02','RR/MM/DD'));
Insert into SONG.PRODUCT (PRO_CODE,PRO_NAME,PRO_PRICE,PRO_QUANTITY,PRO_DATE) values ('0422210201','귤색 폴리하의',30000,23,to_date('19/04/02','RR/MM/DD'));
Insert into SONG.PRODUCT (PRO_CODE,PRO_NAME,PRO_PRICE,PRO_QUANTITY,PRO_DATE) values ('0830110001','풀색 코튼 하의',20000,22,to_date('19/04/02','RR/MM/DD'));
Insert into SONG.PRODUCT (PRO_CODE,PRO_NAME,PRO_PRICE,PRO_QUANTITY,PRO_DATE) values ('1210001001','바다색 데님 상의',30000,23,to_date('19/04/02','RR/MM/DD'));
Insert into SONG.PRODUCT (PRO_CODE,PRO_NAME,PRO_PRICE,PRO_QUANTITY,PRO_DATE) values ('1321102201','파랑색 기모 상의',30000,23,to_date('19/04/02','RR/MM/DD'));
REM INSERTING into SONG.TRANSACTION
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SONG"."CUSTOMER_PK" ON "SONG"."CUSTOMER" ("CUS_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCT_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SONG"."PRODUCT_PK1" ON "SONG"."PRODUCT" ("PRO_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRANSACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SONG"."TRANSACTION_PK" ON "SONG"."TRANSACTION" ("TRA_ORDER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "SONG"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUS_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SONG"."CUSTOMER" MODIFY ("CUS_DATA" NOT NULL ENABLE);
  ALTER TABLE "SONG"."CUSTOMER" MODIFY ("CUS_NAME" NOT NULL ENABLE);
  ALTER TABLE "SONG"."CUSTOMER" MODIFY ("CUS_NUMBER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "SONG"."PRODUCT" ADD CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("PRO_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SONG"."PRODUCT" MODIFY ("PRO_DATE" NOT NULL ENABLE);
  ALTER TABLE "SONG"."PRODUCT" MODIFY ("PRO_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "SONG"."PRODUCT" MODIFY ("PRO_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SONG"."PRODUCT" MODIFY ("PRO_NAME" NOT NULL ENABLE);
  ALTER TABLE "SONG"."PRODUCT" MODIFY ("PRO_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "SONG"."TRANSACTION" MODIFY ("PRO_CODE" NOT NULL ENABLE);
  ALTER TABLE "SONG"."TRANSACTION" MODIFY ("CUS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SONG"."TRANSACTION" ADD CONSTRAINT "TRA_ORDER" PRIMARY KEY ("TRA_ORDER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SONG"."TRANSACTION" MODIFY ("TRA_SALE" NOT NULL ENABLE);
  ALTER TABLE "SONG"."TRANSACTION" MODIFY ("TRA_DATE" NOT NULL ENABLE);
  ALTER TABLE "SONG"."TRANSACTION" MODIFY ("TRA_PRICE" NOT NULL ENABLE);
  ALTER TABLE "SONG"."TRANSACTION" MODIFY ("TRA_QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "SONG"."TRANSACTION" MODIFY ("TRA_ORDER" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION
--------------------------------------------------------

  ALTER TABLE "SONG"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK1" FOREIGN KEY ("PRO_CODE")
	  REFERENCES "SONG"."PRODUCT" ("PRO_CODE") ENABLE;
  ALTER TABLE "SONG"."TRANSACTION" ADD CONSTRAINT "TRANSACTION_FK2" FOREIGN KEY ("CUS_NUMBER")
	  REFERENCES "SONG"."CUSTOMER" ("CUS_NUMBER") ENABLE;
